api/urls.py
from django.urls import path

from .views import *

app_name = 'api'

urlpatterns = [
    path('product/list', ProductViewList.as_view()),
    path('basket/list', BasketViewList.as_view()),
    path('signup',signup),
    path('get_token',get_token),

]

orders/urls.py
from django.urls import path
from .views import SuccerssView, CanceledView
from .views import *


app_name = 'orders'

urlpatterns = [
    path('create/',OrderCreateView.as_view(), name='order_create'),
    path('success/',SuccerssView.as_view(), name='order_success'),
    path('cancel/',CanceledView.as_view(), name='order_canceled'),
    path('cancel/',CanceledView.as_view(), name='order_canceled'),
]

product/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from .views import *

app_name = 'products'

urlpatterns = [
    path('',ProductListView.as_view(), name='list'),
    path('category/<int:category_id>/', ProductListView.as_view(), name='category'),
    path('page/<int:page>/', ProductListView.as_view(), name='paginator'),
    path('baskets/add/<int:product_id>/', BasketView.add_basket, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', BasketView.basket_remove, name='basket_remove'),
]

test_store/urls.py
from django.contrib import admin
from django.urls import path, include
from product import views as product_views
from django.conf.urls.static import static
from django.conf import settings
from orders.views import my_webhook_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', product_views.IndexView.as_view(), name='index'),
    path('products/', include('product.urls', namespace='products')),
    path('users/', include('user.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', my_webhook_view, name ='webhook'),
    path('api/', include('api.urls', namespace ='api')),


]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/',include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from user.models import User


class ProductCategory(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='product_images')
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.name

class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        total = sum([basket.sum() for basket in self])
        return total

    def total_quant(self):
        quant = sum([basket.quantity for basket in self])
        return quant


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт {self.product.name}'

    def sum(self):
        return self.quantity * self.product.price

product/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, HttpResponseRedirect
from .models import Product, ProductCategory, Basket
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from common.views import TitleMixin



# Create your views here.


class IndexView(TitleMixin, TemplateView):
    template_name = 'product/index.html'
    title = 'Store'


class ProductListView(TitleMixin, ListView):
    model = Product
    template_name = 'product/products.html'
    paginate_by = 3
    title = 'Store - Каталог'

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['category'] = ProductCategory.objects.all()
        return context

    def get_queryset(self):
        queryset = super(ProductListView, self).get_queryset()
        category_id = self.kwargs.get('category_id', None)
        if category_id:
            queryset = queryset.filter(category_id=category_id)
        return queryset


class BasketView:
    @staticmethod
    @login_required
    def add_basket(request, product_id):
        product = Product.objects.get(id=product_id)
        baskets = Basket.objects.filter(user=request.user, product=product)
        if not baskets.exists():
            Basket.objects.create(user=request.user, product=product, quantity=1)
        else:
            basket = baskets.first()
            basket.quantity += 1
            basket.save()

        return HttpResponseRedirect(request.META['HTTP_REFERER'])

    @staticmethod
    @login_required
    def basket_remove(request, basket_id):
        basket = Basket.objects.get(id=basket_id)
        basket.delete()
        return HttpResponseRedirect(request.META['HTTP_REFERER'])


# def index(request):
#     return render(request, 'product/index.html')


# def products(request,category_id=None,page= 1):
#     if category_id:
#         product = Product.objects.filter( category_id=category_id)
#     else:
#         product = Product.objects.all()
#     per_page = 3
#     paginator = Paginator(product, per_page)
#     products_paginator = paginator.page(page)
#     context = {
#         'title': 'Store - Каталог',
#         'products': products_paginator,
#         'category': ProductCategory.objects.all()
#             }
#
#     return render(request, 'product/products.html', context=context)


# @login_required
# def add_basket(request, product_id):
#     product = Product.objects.get(id=product_id)
#     baskets = Basket.objects.filter(user=request.user, product=product)
#     if not baskets.exists():
#         Basket.objects.create(user=request.user, product=product, quantity=1)
#     else:
#         basket = baskets.first()
#         basket.quantity += 1
#         basket.save()
#
#     return HttpResponseRedirect(request.META['HTTP_REFERER'])
#
#
# @login_required
# def basket_remove(request, basket_id):
#     basket = Basket.objects.get(id=basket_id)
#     basket.delete()
#     return HttpResponseRedirect(request.META['HTTP_REFERER'])

product/templates/product/baskets.html
{% if baskets %}
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Корзина <span class="badge badge-secondary badge-pill">{{ baskets.total_quant }}</span>
    </h4>
    {% for basket in baskets %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ basket.product.name }}</h5>
                <p class="card-text">{{ basket.product.description }}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item bg-light">
                    <div class="row text-center">
                        <div class="col-lg-4">
                            <input name="basketID" type="number" class="form-control"
                                   value="{{ basket.quantity }}" min="0">
                        </div>
                        <div class="col-lg-4">{{ basket.sum }}</div>
                        <div class="col-lg-4">
                            <a href="{% url 'products:basket_remove' basket.id %}">
                                <i class="fas fa-trash"></i>
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    {% endfor %}

    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">Итого</p>
            <h4 class="float-right">{{ baskets.total_sum }}.</h4>
        </div>
    </div>
    <a class="btn btn-success btn-lg float-right" href="{% url 'orders:order_create' %}">
        Оформить заказ
    </a>
{% else %}
    <h4 class="mt-3 mb-3 text-center">
        Корзина пуста
    </h4>
{% endif %}

product/templates/product/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link href="{% static "/vendor/css/index.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Store</h1>
                <p>
                    Новые образы и лучшие бренды на Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:list' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

product/templates/product/products.html
{% extends 'base.html' %}
{% load static %}
{% load cache %}

{% block title %}
    {{ title }}
{% endblock %}

{% block css %}
    <link href="{% static  "vendor/css/products.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">Store</h1>
                <div class="list-group">
                    {% for category in category %}
                        <a href="{% url 'products:category' category.id %}" class="list-group-item">{{ category }}</a>
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static "/vendor/img/slides/slide-1.jpg" %}"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static "/vendor/img/slides/slide-2.jpg" %}"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static "/vendor/img/slides/slide-3.jpg" %}"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">
                {% cache 30 object_list %}
                    {% for product in object_list %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img class="card-img-top"
                                         src={{ product.image.url }}
                                                 alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="#">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price }}</h5>
                                    <p class="card-text">{{ product.description }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a class="btn btn-outline-success"
                                       href="{% url 'products:basket_add' product.id %}">Отправить в корзину</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endcache %}
                </div>
            {% if is_paginated %}
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %} ">
                            <a class="page-link"
                               href="{% if page_obj.has_previous %} {% url  'products:paginator' page_obj.previous_page_number %} {% else %} # {% endif %} "
                               tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                        {% for page in page_obj.paginator.page_range %}
                            <li class="page-item"><a class="page-link" href="{% url 'products:paginator' page %}">{{ page }}</a></li>
                        {% endfor %}
                        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if page_obj.has_next %} {% url  'products:paginator' page_obj.next_page_number %} {% else %} # {% endif %} ">Next</a>
                        </li>
                    </ul>
                </nav>
            {% endif %}
            </div>

        </div>

    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Store 2022</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}