api/urls.py
from django.urls import path

from .views import *

app_name = 'api'

urlpatterns = [
    path('product/list', ProductViewList.as_view()),
    path('basket/list', BasketViewList.as_view()),
    path('signup',signup),
    path('get_token',get_token),

]

product/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from .views import *

app_name = 'products'

urlpatterns = [
    path('',ProductListView.as_view(), name='list'),
    path('category/<int:category_id>/', ProductListView.as_view(), name='category'),
    path('page/<int:page>/', ProductListView.as_view(), name='paginator'),
    path('baskets/add/<int:product_id>/', BasketView.add_basket, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', BasketView.basket_remove, name='basket_remove'),
]

test_store/urls.py
from django.contrib import admin
from django.urls import path, include
from product import views as product_views
from django.conf.urls.static import static
from django.conf import settings
from orders.views import my_webhook_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', product_views.IndexView.as_view(), name='index'),
    path('products/', include('product.urls', namespace='products')),
    path('users/', include('user.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', my_webhook_view, name ='webhook'),
    path('api/', include('api.urls', namespace ='api')),


]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/',include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('login/',UserLoginView.as_view(), name='login'),
    path('registration/',UserRegistrationView.as_view(), name='register'),
    path('profile/<int:pk>/',login_required(UserProfileView.as_view()), name='profile'),
    path('logout/',LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/',EmailVerificationView.as_view(), name='email_verification'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %}

    {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:list' %}">Каталог <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user-circle"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'users:profile' user.id%}">Профиль</a>
                            </li>
                            <li><a class="dropdown-item" href="orders/orders.html">Заказы</a></li>
                            {% if user.is_superuser or user.is_staff %}
                            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ-панель</a></li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">
                                    Выйти
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static "/vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static "/vendor/fontawesome/fontawesome-icons.js" %}" crossorigin="anonymous"></script>

</body>

</html>

templates/user_base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %} {% endblock %}</title>
    <link href="{% static "vendor/css/auth.css" %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        {% block main %}

        {% endblock %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static "vendor/js/auth-admin.js" %}"></script>
</body>
</html>